export const ClubsHelperArr = [
    {
        id: 1,
        name: 'Detlic',
        email: 'detlic@detlic.com',
        address: 'Djure danicica 3',
        phone: '3211155',
        webAddress:  'https://www.crvenazvezda.com',
        facebookLink: 'https://facebook.com/detlic',
        instagramLink: 'https://instagram.com/instadetlic',
        profileImageUrl: 'https://n6-img-fp.akamaized.net/free-vector/fitness-and-gym-logo_7888-2.jpg?size=338&ext=jpg',
        score: 4.5,
        skillsArr: [1],
        imagesArr: [1,2,3],
        countyId: 2,
    },
    {  
        id:2,
        name: 'Djokovic',
        email: 'djokovic.novak@gmail.com',
        address: '2',
        phone: '3211155',
        webAddress:  'https://www.crvenazvezda.com',
        facebookLink: 'https://facebook.com/detlic',
        instagramLink: 'https://instagram.com/instadetlic',
        profileImageUrl: 'https://n6-img-fp.akamaized.net/free-vector/fitness-and-gym-logo_7888-2.jpg?size=338&ext=jpg',
        score: 6.5,
        skillsArr: [2],
        imagesArr: [4,5,6],
        countyId: 3,
    },
    {  
        id: 3,
        name: 'Postgres',
        email: 'postgres@postyy.com',
        address: 'Djure danicica 3',
        phone: '0612224433',
        webAddress:  'https://www.postgres.com',
        facebookLink: 'https://facebook.com/postgres',
        instagramLink: 'https://instagram.com/instapostgre',
        profileImageUrl: 'https://n6-img-fp.akamaized.net/free-vector/fitness-and-gym-logo_7888-2.jpg?size=338&ext=jpg',
        score: 1.5,
        skillsArr: [1],
        imagesArr: [7,8,9],
        countyId: 3,
    },
    {  
        id: 4,
        name: 'Steva',
        email: 'steva@hugoboss.com',
        address: 'Malog mokrog luga 33',
        phone: '062188662',
        webAddress:  'https://www.steva.com',
        facebookLink: 'https://facebook.com/supersteva',
        instagramLink: 'https://instagram.com/instasteva',
        profileImageUrl: 'https://n6-img-fp.akamaized.net/free-vector/fitness-and-gym-logo_7888-2.jpg?size=338&ext=jpg',
        score: 9.3,
        skillsArr: [2],
        imagesArr: [10,11,12],
        countyId: 1,
    },
];

export const MembershipFeesArr = [
    {
        price: 3300,
        trainingSkill: 1,
        clubClId: 1,
    },
    {
        price: 2300,
        trainingSkill: 1,
        clubClId: 3,
    },
    {
        price: 1300,
        trainingSkill: 2,
        clubClId: 2,
    },
    {
        price: 5300,
        trainingSkill: 2,
        clubClId: 4,
    },
]

export const WorkingTimesArr = [
    {
        workDayFrom: 8,
        workDayTo: 22,
        satFrom: 5,
        satTo: 20,
        sunFrom: 10,
        sunTo: 20,
        clubClId: 1,
    },
    {
        workDayFrom: 8,
        workDayTo: 22,
        satFrom: 5,
        satTo: 20,
        sunFrom: 10,
        sunTo: 20,
        clubClId: 2,
    },
    {
        workDayFrom: 8,
        workDayTo: 22,
        satFrom: 5,
        satTo: 20,
        sunFrom: 10,
        sunTo: 20,
        clubClId: 3,
    },
    {
        workDayFrom: 8,
        workDayTo: 22,
        satFrom: 5,
        satTo: 20,
        sunFrom: 10,
        sunTo: 20,
        clubClId: 4,
    },
];

export const ClubGalleryArr = [
    {
        fileUrl: 'https://keralainformation.com/directory/wp-content/uploads/2014/08/fitness03.jpg',
        clubClId: 1,
    },
    {
        fileUrl: 'https://keralainformation.com/directory/wp-content/uploads/2014/08/fitness03.jpg',
        clubClId: 2,
    },
    {
        fileUrl: 'https://keralainformation.com/directory/wp-content/uploads/2014/08/fitness03.jpg',
        clubClId: 3,
    },
    {
        fileUrl: 'https://keralainformation.com/directory/wp-content/uploads/2014/08/fitness03.jpg',
        clubClId: 4,
    },
]