export const FisioArr = [
    {
        password: 'AAVVN$$@',
        email: 'fica-ficoki@ficoki.com',
        firstName: 'saint Laurent',
        lastName: 'Ivy',
        facebookLink: 'https://www.facebook.com/sain-laurenty',
        instagramLink: 'https://www.instagram.com/sainty-laurenty',
        imageUrl: 'https://www.ficoki.com/image.png',
        cellPhone: '0612223311',
        about: 'sadasdsdsasad stakl aslkdjsalkdj alkdn saldnsa lknalsknlsak nslk nl',
        birthPlace: 'Belgrade Serbia',
        birthDay: 'Slippery',
        fisioSkillsArr: [1,3,5],
        countyArr: [1,2],
        comesHome: false,
        score: 1.6,
        confirmed: true,
    },
    {
        password: 'a;kwop110',
        email: 'steve-aoki@gmail.com',
        firstName: 'Diesel',
        lastName: 'Replay',
        facebookLink: 'https://www.facebook.com/mirjana-cvetanovic',
        instagramLink: 'https://www.instagram.com/uvrnutasnicla',
        imageUrl: 'https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.0-9/14063783_10207048641123109_1854501353913504605_n.jpg?oh=495e54a6369ebf388ef9f7b686da24d6&oe=5B17E7E7',
        cellPhone: '0692224443',
        about: 'asdkalsjdkahdf klahdakjbsd wkbqlqw eqe qwe wq wqw qe trry  42 13 re fa vsf bs gs',
        birthPlace: 'Belgrade Serbia',
        birthDay: '19.12.1999',
        fisioSkillsArr: [1],
        countyArr: [1],
        comesHome: true,
        score: 4.6,
        confirmed: true,
    },
    {
        password: 'a;kasp110',
        email: 'aoki@gmail.com',
        firstName: 'Jovana',
        lastName: 'Popovic',
        facebookLink: 'https://www.facebook.com/popovicka',
        instagramLink: 'https://www.instagram.com/brzo-lezi',
        imageUrl: 'https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.0-9/24059065_10155733782641590_1847903958286317241_n.jpg?oh=13d415f54a0d11664f573a97895af7d2&oe=5B0A3C3E',
        cellPhone: '06922212343',
        about: 'asdkalsjdkahdf sadjl flksad;kjsadl n kasdnsajnd dasjflanklahdakjbsd wkbqlqw eqe qwe wq wqw qe trry  42 13 re fa vsf bs gs',
        birthPlace: 'Pancevo Serbia',
        birthDay: '19.12.1988',
        fisioSkillsArr: [2],
        countyArr: [2],
        comesHome: false,
        score: 9.0,
        confirmed: true,
    },
    {
        password: 'asap@p110',
        email: 'coko-moksi@gmail.com',
        firstName: 'Jurisava',
        lastName: 'Mongoliza',
        facebookLink: 'https://www.facebook.com/mnogo-me-mrzi',
        instagramLink: 'https://www.instagram.com/tusam-stobom',
        imageUrl: 'https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.0-9/24059065_10155733782641590_1847903958286317241_n.jpg?oh=13d415f54a0d11664f573a97895af7d2&oe=5B0A3C3E',
        cellPhone: '06924543',
        about: 'sf;djksgjk lkanan a sa sa sad sa r wea wr ar awaw a waw aawwwaawa we  yr rt r4r',
        birthPlace: 'Vrsac Serbia',
        birthDay: '09.11.1978',
        fisioSkillsArr: [2, 7],
        countyArr: [3, 5],
        comesHome: true,
        score: 9.9,
        confirmed: true,
    },
    {
        password: 'asapsone@p110',
        email: 'cokoladica@gmail.com',
        firstName: 'Mirkson',
        lastName: 'Jokimi',
        facebookLink: 'https://www.facebook.com/youknowmyfunction',
        instagramLink: 'https://www.instagram.com/zauvekzajedno',
        imageUrl: 'https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.0-9/11880682_10206866637161892_7613968873279304540_n.jpg?oh=67959457511c7310b189710f41a921dd&oe=5ADDE4BA',
        cellPhone: '069211111',
        about: 'sf;djksgjk lkasadaslkdhaskd ksa bsdkbsa bdsb asdkb sabd ksa bdaksnan a sa sa sad sa r wea wr ar awaw a waw aawwwaawa we  yr rt r4r',
        birthPlace: 'Beograd Serbia',
        birthDay: '09.11.1978',
        fisioSkillsArr: [ 5, 7],
        countyArr: [3, 5],
        comesHome: true,
        score: 9.0,
        confirmed: true,

    },
 ]

 export const FisioCountyArr = [
     {
         price: 2000,
         address: 'Visnjicka 5a',
         saloonName: 'Gotk klub',
         fisioClId: 1,
         fisioCategoriesId: 1,
         countyId: 1,
     },
     {
        price: 1000,
        address: 'Svetosavska 21',
        saloonName: 'Rokanje klub',
        fisioClId: 1,
        fisioCategoriesId: 3,
        countyId: 2,
    },
    {
        price: 1800,
        address: 'Visnjicka 5a',
        saloonName: 'Gotk klub',
        fisioClId: 1,
        fisioCategoriesId: 5,
        countyId: 2,
    },
    {
        price: 1800,
        address: 'Visnjicka 5a',
        saloonName: 'Gotk klub',
        fisioClId: 2,
        fisioCategoriesId: 1,
        countyId: 1,
    },
    {
        price: 1200,
        address: 'Plug 5a',
        saloonName: 'Gwwww klub',
        fisioClId: 3,
        fisioCategoriesId: 2,
        countyId: 2,
    },
    {
        price: 1100,
        address: 'Drop that 5a',
        saloonName: 'Gotk klub',
        fisioClId: 4,
        fisioCategoriesId: 2,
        countyId: 3,
    },
    {
        price: 1100,
        address: 'Drop that 5a',
        saloonName: 'Gotk klub',
        fisioClId: 4,
        fisioCategoriesId: 7,
        countyId: 5,
    },
    {
        price: 1100,
        address: 'Drop that 5a',
        saloonName: 'Gotk klub',
        fisioClId: 5,
        fisioCategoriesId: 5,
        countyId: 3,
    },
    {
        price: 1100,
        address: 'Drop that 5a',
        saloonName: 'Gotk klub',
        fisioClId: 5,
        fisioCategoriesId: 7,
        countyId: 5,
    },
 ]
